= `Punch` in Golang
:toc:
:gorewrite_start: 795c79a537f9fe082188ccd94cebcf549962c589
:gorewrite_end: 1b628b4912a942949fb7167b4851e69668593c83
:punchsh_newest: https://github.com/jzacsh/punch/blob/a1e40862a7203613cd6f0ccc331ac68f737ab329/bin/punch
:punchsh_oldest: https://github.com/jzacsh/bin/commit/f7fbddec97ad9f9bade2ca69e3d531b99b52dbc4
:punchsh_follow: https://github.com/jzacsh/bin/commit/021340fcdde241080206f
:batsexec: https://gist.github.com/jzacsh/65fb4df01e3dbf23a2a4#file-test-sh
:gotestingmain: https://golang.org/pkg/testing/#hdr-Main
:gorewrite_gisturl: https://gist.github.com/jzacsh/0f09b34e45211e76172362c10f437cd3
:git_merge_cmd: git merge --log --strategy=recursive -Xtheirs gistgolang/master

`punch` simply manages an <<dbschema, Sqlite3 time-tracking table>> that helps
me record hours spent on various tasks. This repo is a golang <<rewrite, rewrite>>
footnoteref:[gorewrite, from `{gorewrite_start}` to `{gorewrite_end}`] of the
Bash script that managed that sqlite table, using a nearly identical command-line
API.

== Quick Start

.quick installation
----
$ go get github.com/jzacsh/punch/cmd/punch
----
Alternatively, to build `punch` with a custom name and/or have version info
built into the binary, use the output of `make` _(in dev steps below)._

.usage: `$PUNCH_CARD` environment variable required
----
$ export PUNCH_CARD="$HOME"/punchcard # or wherever you'd like it to live
$ echo 'export PUNCH_CARD="$HOME"/punchcard' >> ~/.bashrc
----
For first-time usage: `punch` will offer to automatically create the database at
`$PUNCH_CARD`, so long as the environment variable isn't empty.

.commands: docs are built into the binary
`punch h` for a quick command pattern listing, or the `--help` for full the doc
_(this includes a section of example commands)_.

== Development

.prerequisites
----
$ go get github.com/mattn/go-sqlite3
----

`make punch` to build. no tests written, yet.

.helpful reference punchcard
----
$ cd cmd/punch
$ make
$ ./punch # will throw error without a $PUNCH_CARD

$ export PUNCH_CARD=./testdata/sample.card

# can now edit, build, manually test results without upsetting `punch`
$ $EDIT *.go; make; ./punch
----

.why the `./cmd/punch` hierarchy?
If/when I ever want to share this logic outside of the CLI, this should allow me
to refactor all of `main` pkg's generic logic into a top-level library.

.tests?
Nope, but it's a <<TODO>>

=== Status

Punch is complete: it does what I need and I likely won't add anything to it.
None the less, if I do anything next, hopefully it'll be one of the below:

[[TODO]]
.TODO
. take human-readable times as input; allow for `@` syntax for exact stamps,
  like `date` does.
. building upon `query -last`: report on duration accrued (ie: in `punchcard`
  table) since `-last` value (per `paychecks` table)
. add debugging flag that:
.. print all SQL statements before they run
.. tackles TODOs beside `stmt.Exec(...)` calls that drop debug info on the floor
. *test coverage* either, or both of:
.. *unit tests*; eg: flooding `main` pkg w/multiple `*_test.go` files, just as
   that package already does with its current division of logic
.. *e2e testing*; eg: using my {batsexec}[drop-in script `test.sh` from BATS]
   footnoteref:[e2emocking, The `punch` cmd starts at `cli.go`. I'm imagining
   having an alternative wrapper *before* to `func main()` of `cli.go`
   {gotestingmain}[where I can take the opportunity to pollute the environment]
   with a mock-clock `import` and set its time to whatever is passed on the
   commandline for testing _(eg: if the test-punch binary is called with '1234'
   then '1234' wil be what it the rest of `punch` sees as `time.Now()`)_]

[[dbschema]]
== Data `Punch` Manages

`punch` is primarily concerned with one table: `punchcard`, but also has a
feature that relies on a smaller extra table called `paychecks`

NOTE: Trust the `INSERT` SQL statements in `create.go` over this documentation
of punch's underlying schema.

.`punchcard`: tracks sessions working on something
[options="header"]
|====
| field name | type | required | notes

| `punch` | integer | required | primary key; UNIX timestamp in seconds
| `status` | integer | required |
  always `1` or `0`, ie: pseudo Boolean footnoteref:[punchstatus, code would
  likely be a lot simpler if I'd not <<rewrite, ported>> this over and just had
  inferred its equivalent meaning at run-time... oh well]
| `project` | integer | required | not primary footnoteref:[punchprimkey,
  'project' _should_ be included in primary key constraint along with 'punch'
  but it isn't]
| `note` | string | optional | free-form, user-composed string
|====

.`paychecks`: tracks bills sent per blocks of `punchcard` sessions
[options="header"]
|====
| field name | type | required | attributes

| `startclusive` | int | required |
  Unix timestamp in seconds to include in this billing period
| `endclusive` | int | required |
  End-boundary version of 'startclusive'. +
  Note: both fields will only ever _incidentally_ match a "punch" value of the
  `punchcard` table
| `project` | string | required | foreign key to `punchcard`
| `note` | string | optional | free-form, user-composed string
|====


== Strange Project, Strange Git History

[[rewrite]]
.WhyTF Does `punch` Exist? Why'd You Write it Twice??
Originally `punch` was a Bash script I wrote years ago "_{punchsh_oldest}[to
learn how to use `getopts`]_". I finished it, forgot about it, then actually
started using it to track freelance hours, at which point the script was working
fine (if a little frightening footnoteref:[bashpunch, the
{punchsh_newest}[`bin/punch` script] that I ultimately ported to golang was
already a thousand lines of bash 4 without test coverage]).

I ported footnoteref:[gorewrite] to golang _partly_ because that much
footnoteref:[bashpunch] Bash scares me now-a-days, _partly_ because I wanted an
excuse to play with golang, _partly_ because I wanted to veg out
footnoteref:[gistport, rewrite was from scratch in {gorewrite_gisturl}[a gist]
and merged into this repo with `{git_merge_cmd}`] on Spring break while back in my undergrad.
