= `Punch` in Golang
:punchsh: https://github.com/jzacsh/punch/tree/a1e40862a7
:batsexec: https://gist.github.com/jzacsh/65fb4df01e3dbf23a2a4#file-test-sh

See original punch implementation here:
  {punchsh}[`bin/punch` script of github.com/jzacsh/punch]
_(a thousand lines of bash 4 without test coverage)_

== Development

.prerequisites
----
$ go get github.com/mattn/go-sqlite3
----

`make punch` to build. no tests written, yet.

.helpful sample punchcard
----
$ make
$ ./punch # will throw error without a $PUNCH_CARD
$ export PUNCH_CARD=./sample.card
$ ./punch # will now be happy, having a usable card
----

== Status

Intentions: I'm currently writing this for fun on spring break, because I miss
writing code. No idea if I have any plans to ever finish this.


As of git tag `v0.complete` the `query` and `punch` subcommands are basically
complete, giving this implementation min-viable feature parity with with the
original {punchsh}[shell implementation's level of completion] (the remaining
features, of which, should probably be ripped out anyway). Still, yet to do:

.TODO
. *e2e testing*; eg: using my {batsexec}[drop-in script `test.sh` from BATS]
